### ISSUE TITLE
UNIX socket support

### ISSUE THREAD

**Issue by symisc** [dmitigr/fcgi#1]
Hey @dmitigr,

Does your implementation support UNIX sockets instead of TCP binding? Most modern implementation like php-fcm do rely on UNIX sockets instead of TCP to reduce network congestion and increase responses ratio.

**Comment by dmitigr** [comment]
Hello,

Yes. Please use Listener_options::make(std::filesystem::path path, int backlog) constructor function to make a listener of the Unix Domain Sockets.

PS. There are also support for Windows Named Pipes.
