### ISSUE TITLE
conn->out() can parse multiple lines?

### ISSUE THREAD

**Issue by AlexeyRoza** [dmitigr/fcgi#3]
hello
why conn->out() only allows single line and when i make two of them server breaks with:
fcgi-hellomt.cpp:25:24: error: missing terminating " character
   25 |         conn->out() << "<!doctype html>

I'm only trying this:
conn->out() << "<!doctype html>
<html>";

**Comment by dmitigr** [comment]
Hey,

It doesn't issue of the library, but the syntax error of your code. If you want to write a multi-line literal you need to use raw literals, for example:

```c++
conn->out() << R"(<!doctype html>
<html>
</html>
)";

**Comment by AlexeyRoza** [comment]
точно, спасибо
а где сейчас документация? Была тут: https://github.com/dmitigr/cefeika/blob/ffc99005699e5e808a3107b55d55821f01ac59ec/fcgi/

**Comment by dmitigr** [comment]
> а где сейчас документация?

Сейчас только в исходниках. Скоро будет на dmitigr.ru (в разработке). Если что-то не понятно, можете спрашивать.
